### ISSUE TITLE
Enable token refresh for ACR

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr-docker-credential-helper#1]
The main goal of this issues it to address the need for a credential helper that can refresh an access token provided by AAD and make sure that the credential helper is updated with the latest token. 
This works the AAD capability of ACR - described in Azure/acr#32

**Comment by shhsu** [comment]
This is done https://github.com/Azure/acr-docker-credential-helper/commit/414181ae135e19c8eb234351ae7110c175bd2296
