### ISSUE TITLE
macOS: running the installer a second time always fails

### ISSUE THREAD

**Issue by DavidObando** [Azure/acr-docker-credential-helper#11]
The installer will create a backup of the .config file, but if the backup already exists the operation is aborted.

Additionally, the prompt says:
```
Please note that bak file will be overwritten, continue? [Y/y]
```
This needs 2 changes:
  1. Yes/No prompts should say [Y/n] where the upper case letter signifies the default option.
  2. It's unclear what the bak file is unless you know the implementation details. I'd argue you should overwrite without prompting, but I can be convinced otherwise.

**Comment by shhsu** [comment]
https://github.com/Azure/acr-docker-credential-helper/pull/13

**Comment by shhsu** [comment]
changes merged
