### ISSUE TITLE
macOS: docker logout ungracefully succeeds with the acr cred helper

### ISSUE THREAD

**Issue by DavidObando** [Azure/acr-docker-credential-helper#12]
Running docker logout succeeds with exit code 1. By succeeds I mean we do actually log out, but the process sends an error signal for some reason.

**Comment by shhsu** [comment]
@SajayAntony I need a macOS to test this issue

**Comment by shhsu** [comment]
it's a docker cli issue https://github.com/docker/cli/issues/204
