### ISSUE TITLE
Linux: installation script should ask for sudo password explicitly

### ISSUE THREAD

**Issue by DavidObando** [Azure/acr-docker-credential-helper#18]
Currently when one does
```bash
curl -L https://aka.ms/acr/installaad/bash | sudo /bin/bash
```
The process will block waiting for the password to be entered, but there's no message making this explicit. In macOS this is more clear because the terminal displays a key symbol, as shown here:
![macOS-key](http://i.stack.imgur.com/nXrSU.png)
However, in Linux it just blocks apparently without any indication of what it's waiting for. We do ask for the password, but there's a race condition by which the password is asked first, then we print the output of the curl command, and then we block.

We should design this to be more user friendly.

**Comment by shhsu** [comment]
https://github.com/Azure/acr-docker-credential-helper/pull/19
