### ISSUE TITLE
Failure to store credentials

### ISSUE THREAD

**Issue by DavidObando** [Azure/acr-docker-credential-helper#21]
I created a container registry and added an external user with a `Monitoring Contributor Service Role` role which contains a longer set of actions, thus making it a longer JWT, in this case with a length of 3241 characters.

If I disable the credential helper (by, then login succeeds. If I enable it, I get this error:
```
Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `The stub received bad data.``
```

**Comment by shhsu** [comment]
Questions:

What OS does this issue occur on?
What is the underlying cred helper?

**Comment by DavidObando** [comment]
I reproduced this on Windows, the underlying cred helper was winstore I assume. I'll sync up with you in person to show you this.

**Comment by shhsu** [comment]
Looks like this is underlying cred helper issue again. If you change the `config.json` file to this, you get the same error

```
{
	"credsStore": "wincred"
}
```

**Comment by shhsu** [comment]
When we were testing token have wildcard "*" permission, the token length was 2403 bytes.  However, when the custom permission level is used this put the token length as over 3K bytes.

WinCred maximum length appears to be 2.5K

**Comment by shhsu** [comment]
2 proposed solution

1. Always use file store so we don't run into this limit
2. Compress the token. I tried using gzip (https://stackoverflow.com/questions/19197874/how-can-i-use-gzip-on-a-string-in-golang). The compressed string is 36% shorter. 3055 vs 1955.

Updated: compression solution will not work because the compressed token will not be in plain text.

**Comment by shhsu** [comment]
This issue does not repo on osxkeychain

**Comment by shhsu** [comment]
Alternative solution
https://github.com/Azure/acr-docker-credential-helper/pull/24

**Comment by shhsu** [comment]
https://github.com/Azure/acr-docker-credential-helper/pull/24 worked around it
