### ISSUE TITLE
Trying to fix integration with Jib

### ISSUE THREAD

**Issue by coollog** [Azure/acr-docker-credential-helper#31]
Currently, we are having trouble using `docker-credential-acr-*` as the credential helpers for authenticating against Azure Container Registry in [Jib](https://github.com/GoogleContainerTools/jib). We would like to solve this issue so that users can use ACR more easily.

I tested out the credential helper with:

```shell
$ az acr login -n jibtest
```

`docker pull jibtest.azurecr.io/jibtestimage` works fine.

However, trying to use the credentials myself did not work.

```shell
$ echo jibtest.azurecr.io | docker-credential-acr-linux get
{"ServerURL":"","Username":"\u003ctoken\u003e","Secret":"<my secret>"}
```

I tried using that in a call to authenticate against `jibtest.azurecr.io` (my test registry):

```shell
$ curl -v https://jibtest.azurecr.io/oauth2/token -u "<token>:<my secret>"
```

It gave `401 Unauthorized`, so I'm assuming this is not the way to authenticate. What is the correct way to authenticate over HTTPS with the credentials outputted from the credential helper?

@loosebazooka
@tadcordle
@patflynn

**Comment by loosebazooka** [comment]
Just bumping this, would be nice to get jib working with acr-docker-credential before a jib GA release.

**Comment by agolomoodysaada** [comment]
Are there any plans to get this issue resolved? It seems mostly an issue with ACR's backend?
I'm happy to help if I could get some pointers from the maintainers

**Comment by andxu** [comment]
Update some snapshots for reproducing this issue:
![image](https://user-images.githubusercontent.com/17075863/51652182-b2ca4a00-1fc9-11e9-9d10-79b2fd5d4165.png)

![image](https://user-images.githubusercontent.com/17075863/51652208-cbd2fb00-1fc9-11e9-8b4e-96adbbe16fb6.png)

**Comment by shizhMSFT** [comment]
`docker-credential-acr-linux get` returns an ACR refresh token.
Please refer to [Authenticating docker with an ACR refresh token](https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#authenticating-docker-with-an-acr-refresh-token).

**Comment by shizhMSFT** [comment]
For details on how to correctly use the refresh token, please refer to
- [Calling POST `/oauth2/token` to get an ACR access token](https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#calling-post-oauth2token-to-get-an-acr-access-token)
- [Token Authentication Implementation](https://docs.docker.com/registry/spec/auth/jwt/)

**Comment by shizhMSFT** [comment]
@coollog Could you have a check if Jib follows the [Credential helper protocol](https://github.com/docker/cli/blob/master/docs/reference/commandline/login.md#credential-helper-protocol) by Docker?

**Comment by andxu** [comment]
@coollog, ACR doesn't support basic username/password authorization but 'token' authorization, see the following example of  request/response:
1. get `identity-token` from docker-credential-acr 
2. get the `access-token` from the `identity-token`
3. use the `access-token` to call image apis

```
----------------------------------------------------------------------------------------------------
executing: az acr login -n andyreg
result:Login Succeeded
----------------------------------------------------------------------------------------------------
executing: echo andyreg.azurecr.io | docker-credential-acr-windows get
{
    "ServerURL": "",
    "Username": "<token>",
    "Secret": "<eyJhbGciOi...88Q>"
}
----------------------------------------------------------------------------------------------------
first try without authorization: GET https://andyreg.azurecr.io/v2/andy/manifests/latest
headers: {
	access-control-expose-headers: Docker-Content-Digest, WWW-Authenticate, Link, X-Ms-Correlation-Request-Id
	connection: close
	content-length: 136
	content-type: application/json; charset=utf-8
	date: Fri, 25 Jan 2019 05:22:46 GMT
	docker-distribution-api-version: registry/2.0
	server: nginx
	strict-transport-security: max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains
	www-authenticate: Bearer realm="https://andyreg.azurecr.io/oauth2/token",service="andyreg.azurecr.io",scope="repository:andy:pull"
	x-content-type-options: nosniff
	x-ms-correlation-request-id: 52aac4cb-bfd8-4864-ba8e-c8d16ff79b2b
}
----------------------------------------------------------------------------------------------------
authorize by information in header "www-authenticate":
POST_ https://andyreg.azurecr.io/oauth2/token
headers: {
	    Content-Type application/x-www-form-urlencoded <MUST be this, "application/x-www-form-urlencoded;charset=UTF-8" doesn't work>
    }
 Body:  grant_type=refresh_token&service=andyreg.azurecr.io&scope=repository:andy:pull&refresh_token=<eyJhbGciOi...88Q>

get access_token back:  {"access_token":"<eyJhbGciOi...3gw>"}
----------------------------------------------------------------------------------------------------
access using access_token: GET https://andyreg.azurecr.io/v2/andy/manifests/latest
GET:https://andyreg.azurecr.io/v2/andy/manifests/latest
Headers:{
    "Accept": "application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v2+json",
    "Authorization": "Bearer <eyJhbGciOi...3gw>"
}
get manifest json:
{ schemaVersion: 2,
  mediaType: 'application/vnd.docker.distribution.manifest.v2+json',
  config:
   { mediaType: 'application/vnd.docker.container.image.v1+json',
     digest:
      'sha256:5910899824b11d0978c7a9fdd86970687a3d9bd4513da6d38e3b3e9b244e7c2d',
     size: 1445 },
  layers:
   [ { mediaType: 'application/vnd.docker.image.rootfs.diff.tar.gzip',
       digest:
        'sha256:d455ccc1cea9edcc50a50e0ee33a9f90c1f45486bacf8cb59e13203d7ee3be66',
       size: 7768687 },
     { mediaType: 'application/vnd.docker.image.rootfs.diff.tar.gzip',
       digest:
        'sha256:ba7c544469e514f1a9a4dec59ab640540d50992b288adbb34a1a63c45bf19a24',
       size: 622796 },
     { mediaType: 'application/vnd.docker.image.rootfs.diff.tar.gzip',
       digest:
        'sha256:12f9f62c1cab33b02b4f332738b03fbcd35fd7906f6fa5ad1acb733056d51cb7',
       size: 38723383 },
     { mediaType: 'application/vnd.docker.image.rootfs.diff.tar.gzip',
       digest:
        'sha256:77da848d3808f0acd881b41f4864a497f056c1049aeb1f582a0290b6a1da14df',
       size: 2476772 },
     { mediaType: 'application/vnd.docker.image.rootfs.diff.tar.gzip',
       digest:
        'sha256:07ff609379c4cc1102bfcbc1287b937b415fec734dea0c677c81b5fa02080d09',
       size: 164 },
     { mediaType: 'application/vnd.docker.image.rootfs.diff.tar.gzip',
       digest:
        'sha256:9bf5edf719a2a5f4eea6ecd4c89610ba032dd087d745f6605f0822dae13e4cb0',
       size: 901 } ] }

```

**Comment by coollog** [comment]
@shizhMSFT @andxu Thanks for the references! It looks like we did not add support for using `<token>` as the username to indicate that the `Secret` provided by the credential helper is an identity token.

[Credential helper protocol](https://github.com/docker/cli/blob/master/docs/reference/commandline/login.md#credential-helper-protocol)
> If the secret being stored is an identity token, the Username should be set to `<token>`.

Once we add support for this, Jib should be able to work with this credential helper.

**Comment by andxu** [comment]
The token for the acr will be expired in our hour, I am asking for whether it can be extended, see
https://github.com/Azure/acr/issues/191

**Comment by andxu** [comment]
The issue is addressed at jib, can close it here.
